// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PaginaInicialDocumentDataSlicesSlice = never;

/**
 * Content for Página Inicial documents
 */
interface PaginaInicialDocumentData {
  /**
   * Slice Zone field in *Página Inicial*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: pagina_inicial.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PaginaInicialDocumentDataSlicesSlice> /**
   * Meta Title field in *Página Inicial*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: pagina_inicial.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Página Inicial*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: pagina_inicial.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Página Inicial*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: pagina_inicial.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Página Inicial document from Prismic
 *
 * - **API ID**: `pagina_inicial`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PaginaInicialDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PaginaInicialDocumentData>,
    "pagina_inicial",
    Lang
  >;

export type AllDocumentTypes = PaginaInicialDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PaginaInicialDocument,
      PaginaInicialDocumentData,
      PaginaInicialDocumentDataSlicesSlice,
      AllDocumentTypes,
    };
  }
}
