// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  carrossel: dynamic(() => import("./Carrossel")),
  ofertas: dynamic(() => import("./Ofertas")),
  sessoes: dynamic(() => import("./Sessoes")),
};
